name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Necesario para contar commits y obtener hash

      - name: Create config file with real API keys
        run: |
          cat > docs/nai/config.js << 'EOF'
          // Configuración para producción con variables de entorno (GENERADA EN CI)
          const CONFIG = {
            firebase: {
              apiKey: "${{ secrets.FIREBASE_API_KEY }}",
              authDomain: "${{ secrets.FIREBASE_AUTH_DOMAIN }}",
              projectId: "${{ secrets.FIREBASE_PROJECT_ID }}",
              storageBucket: "${{ secrets.FIREBASE_STORAGE_BUCKET }}",
              messagingSenderId: "${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}",
              appId: "${{ secrets.FIREBASE_APP_ID }}",
              measurementId: "${{ secrets.FIREBASE_MEASUREMENT_ID }}"
            },
            gemini: {
              apiKey: "${{ secrets.GEMINI_API_KEY }}"
            }
          };
          window.CONFIG = CONFIG;
          EOF

      - name: Generate version.js
        run: |
          DATE_UTC=$(date -u +%Y-%m-%dT%H:%M:%SZ)
          STAMP=$(date -u +%Y.%m.%d-%H%M%S)
          HASH=$(git rev-parse --short HEAD)
          COUNT=$(git rev-list --count HEAD)
          VERSION="${STAMP}-c${COUNT}-${HASH}"
          mkdir -p docs/nai
          cat > docs/nai/version.js <<EOF
          // Archivo generado automáticamente - NO editar
          // Fecha UTC: $DATE_UTC
          // Versión: $VERSION
          window.__APP_VERSION__ = '$VERSION';
          EOF
          echo "Versión generada: $VERSION"

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
